### ISSUE TITLE
Date customization

### ISSUE THREAD

**Issue by kseistrup** [19WAS85/checkpoints#1]
Is there a way to customize/configure dates so that they are shown as e.g. dd/mm/yyyy or yyyy-mm-dd instead of the US date format?

**Comment by 19WAS85** [comment]
Hey! I have no plans to customization yet. I've used `toLocaleDateString` in dates, so you would seen the locale browser configuration.

**Comment by kseistrup** [comment]
Thanks. That is what was confusing me.

When I open the browser webconsole I get `MM/DD/YYYY hh:mm:ss AM/PM` if I say `new.Date().toLocaleString()`.

If I do the same in nodejs in a terminal I get `DD/MM/YYYY hh.mm.ss` (which is still incorrect, but at least better than the US format).

Time for a new browser. I'm sorry for having bothered you.
